export const cardsData = [
  {
    title: "EARNINGS (MONTHLY)",
    price: "$40,000",
    icon: "fa fa-calendar fa-2x ",
    type: "primary",
  },
  {
    title: "EARNINGS (ANNUAL)",
    price: "$215,000 ",
    icon: "fa fa-dollar fa-2x",
    type: "success",
  },
  {
    title: "TASKS",
    price: "50% ",
    icon: "fa fa-tasks fa-2x",
    type: "info",
  },
  {
    title: "PENDING REQUESTS",
    price: "18",
    icon: "fa fa-comments fa-2x",
    type: "warning",
  },
];

export const tableData = [
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "33",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Angelica Ramos",
    position: "Chief Executive Officer (CEO)",
    office: "London",
    age: "47",
    startDate: "2009/10/09",
    salary: "$1,200,000",
  },
  {
    name: "Ashton Cox",
    position: "Junior Technical Author",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Bradley Greer",
    position: "Software Engineer",
    office: "London",
    age: "41",
    startDate: "2012/10/13",
    salary: "$132,000",
  },
  {
    name: "Brenden Wagner",
    position: "Software Engineer",
    office: "San Francisco",
    age: "28",
    startDate: "2011/06/07",
    salary: "$206,850",
  },
  {
    name: "Airi John",
    position: "Accountant",
    office: "China",
    age: "84",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "25",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Bruno Nash",
    position: "	Software Engineer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Caesar Vance",
    position: "Senior Javascript Developer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Cedric Kelly",
    position: "	Sales Assistant",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "33",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Angelica Ramos",
    position: "Chief Executive Officer (CEO)",
    office: "London",
    age: "47",
    startDate: "2009/10/09",
    salary: "$1,200,000",
  },
  {
    name: "Ashton Cox",
    position: "Junior Technical Author",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Bradley Greer",
    position: "Software Engineer",
    office: "London",
    age: "41",
    startDate: "2012/10/13",
    salary: "$132,000",
  },
  {
    name: "Brenden Wagner",
    position: "Software Engineer",
    office: "San Francisco",
    age: "28",
    startDate: "2011/06/07",
    salary: "$206,850",
  },
  {
    name: "Airi John",
    position: "Accountant",
    office: "China",
    age: "84",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "25",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Bruno Nash",
    position: "	Software Engineer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Caesar Vance",
    position: "Senior Javascript Developer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Cedric Kelly",
    position: "	Sales Assistant",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "33",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Angelica Ramos",
    position: "Chief Executive Officer (CEO)",
    office: "London",
    age: "47",
    startDate: "2009/10/09",
    salary: "$1,200,000",
  },
  {
    name: "Ashton Cox",
    position: "Junior Technical Author",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Bradley Greer",
    position: "Software Engineer",
    office: "London",
    age: "41",
    startDate: "2012/10/13",
    salary: "$132,000",
  },
  {
    name: "Brenden Wagner",
    position: "Software Engineer",
    office: "San Francisco",
    age: "28",
    startDate: "2011/06/07",
    salary: "$206,850",
  },
  {
    name: "Airi John",
    position: "Accountant",
    office: "China",
    age: "84",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "25",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Bruno Nash",
    position: "	Software Engineer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Caesar Vance",
    position: "Senior Javascript Developer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Cedric Kelly",
    position: "	Sales Assistant",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "33",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Angelica Ramos",
    position: "Chief Executive Officer (CEO)",
    office: "London",
    age: "47",
    startDate: "2009/10/09",
    salary: "$1,200,000",
  },
  {
    name: "Ashton Cox",
    position: "Junior Technical Author",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Bradley Greer",
    position: "Software Engineer",
    office: "London",
    age: "41",
    startDate: "2012/10/13",
    salary: "$132,000",
  },
  {
    name: "Brenden Wagner",
    position: "Software Engineer",
    office: "San Francisco",
    age: "28",
    startDate: "2011/06/07",
    salary: "$206,850",
  },
  {
    name: "Airi John",
    position: "Accountant",
    office: "China",
    age: "84",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "25",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Bruno Nash",
    position: "	Software Engineer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Caesar Vance",
    position: "Senior Javascript Developer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Cedric Kelly",
    position: "	Sales Assistant",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "33",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Angelica Ramos",
    position: "Chief Executive Officer (CEO)",
    office: "London",
    age: "47",
    startDate: "2009/10/09",
    salary: "$1,200,000",
  },
  {
    name: "Ashton Cox",
    position: "Junior Technical Author",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Bradley Greer",
    position: "Software Engineer",
    office: "London",
    age: "41",
    startDate: "2012/10/13",
    salary: "$132,000",
  },
  {
    name: "Brenden Wagner",
    position: "Software Engineer",
    office: "San Francisco",
    age: "28",
    startDate: "2011/06/07",
    salary: "$206,850",
  },
  {
    name: "Airi John",
    position: "Accountant",
    office: "China",
    age: "84",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Airi Satou",
    position: "Accountant",
    office: "Tokyo",
    age: "25",
    startDate: "2008/11/28",
    salary: "$162,700",
  },
  {
    name: "Bruno Nash",
    position: "	Software Engineer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
  {
    name: "Caesar Vance",
    position: "Senior Javascript Developer",
    office: "San Francisco",
    age: "66",
    startDate: "2009/01/12",
    salary: "$86,000",
  },
];

export const chartBar = [
  {
    name: "Server Migration ",
    load: "20%",
    color: "danger",
    width: "20%",
  },
  {
    name: "Sales Tracking ",
    load: "40%",
    color: "warning",
    width: "40%",
  },
  {
    name: "Customer Databas",
    load: "60%",
    width: "60%",
  },
  {
    name: "Payout Details ",
    load: "80%",
    color: "info",
    width: "80%",
  },
  {
    name: "Account Setup ",
    load: "Complet!",
    color: "success",
    width: "100%",
  },
];

export const color = [
  {
    color: "primary",
    text: "Primary",
    small: "#4e73df",
  },
  {
    color: "success",
    text: "Success",
    small: "#1cc88a",
  },
  {
    color: "info",
    text: "Info",
    small: "#36b9cc",
  },
  {
    color: "warning",
    text: "Warning",
    small: "#f6c23e",
  },
  {
    color: "danger",
    text: "Danger",
    small: "#e74a3b",
  },
  {
    color: "secondary",
    text: "Secondary",
    small: "#858796",
  },
];

export const dropdownInfo = [
  {
    color: "primary",
    icon: "fa fa-file fa-lg text-white ",
    text: "December 12, 2020",
    info: "A new monthly report is ready to download !",
  },
  {
    color: "success",
    icon: "fas fa-donate fa-lg text-white",
    text: "December 7, 2020",
    info: "$290.29 has been deposited into your account!",
  },
  {
    color: "warning",
    icon: "fa fa-exclamation-triangle fa-lg text-white align-items-center",
    text: "December 2, 2020",
    info: "Spending Alert: We've noticed unusually high spending for your account.",
  },
];
